// Generated by Factory OS. Do not edit by hand.
export type RevenueRoute = {
  funnel: string;
  productId: string;
  rationale: string;
};

export const revenueRoutes = {
  "rewrite-friendly-text": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "初心者向け言い換え=入口記事"},
  "ai-tool-principle-map": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "陳腐化不安(demand_log由来)への一般向け回答。入口→原理理解の深掘りはZennへ"},
  "brainstorm-ideas": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "企画は有料note週次深掘りの対象テーマ"},
  "build-ai-agent-skill-file": {"funnel": "zenn", "productId": "zenn-builder-kit", "rationale": "技術者向け信頼形成。実装手順をZenn本・技術キットへ接続"},
  "choose-minimal-ai-stack": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "顧客対応を伴う相談ではなく、有料noteの買い切り深掘りへ接続"},
  "compare-options-for-decision": {"funnel": "affiliate_separate_site", "productId": "free-starter-kit", "rationale": "比較・意思決定テーマ。affiliate_lab 転用候補、本体HPは無料キットフォールバック"},
  "explain-technical-terms": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "初心者の理解支援。入口記事"},
  "find-routine-automation": {"funnel": "booth", "productId": "automation-design-pack", "rationale": "顧客対応を伴う相談ではなく、買い切りの自動化設計テンプレートへ接続"},
  "make-checklist": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "テンプレ・仕組み化系"},
  "make-comparison-table": {"funnel": "affiliate_separate_site", "productId": "free-starter-kit", "rationale": "比較・選び方テーマ。収益検証は affiliate_lab 側、本体HPのCTAは無料キットにフォールバック"},
  "make-content-calendar": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "発信の習慣化=運用テンプレート集の対象(クリエイター向け)"},
  "make-learning-plan": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "学習系・個人向け入口"},
  "make-prompt-template": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "テンプレ化テーマ(戦略文書で明示された例)"},
  "make-review-quiz": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "学習系・個人向け入口"},
  "make-slides-outline": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "会社員向け有料note週次深掘りの対象テーマ"},
  "make-sns-post": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "発信運用ワークフロー。テンプレ集域"},
  "make-template": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "テンプレ作成そのもの。BOOTHテンプレ集へ直結"},
  "make-todo-list": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "最も軽い初心者手順。入口"},
  "make-weekly-report": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "会社員向け有料note週次深掘りの対象テーマ"},
  "make-weekly-review": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "運用習慣化テンプレ=運用テンプレート集の対象読者"},
  "meeting-notes-to-minutes": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "議事録は有料note週次深掘りの対象テーマ"},
  "organize-concepts": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "ノート術の基本。スターターキット域"},
  "organize-reading-notes": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "個人のノート習慣入門。スターターキットの基本テンプレ域"},
  "structure-note-article": {"funnel": "booth", "productId": "booth-template-pack", "rationale": "note運用ワークフロー=運用テンプレート集の中核テーマ"},
  "summarize-research-notes": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "調査・要約は有料note週次深掘りの対象テーマ"},
  "write-email-reply": {"funnel": "free_kit", "productId": "free-starter-kit", "rationale": "初心者向け手順記事の代表。無料入口に直結"},
  "write-product-description": {"funnel": "paid_note", "productId": "weekly-paid-note", "rationale": "仕事文章プロンプト。有料note週次深掘りの対象テーマ"},
} satisfies Record<string, RevenueRoute>;

export function getRevenueRoute(slug: string): RevenueRoute | undefined {
  return revenueRoutes[slug as keyof typeof revenueRoutes];
}
